export const matyrs = [
  {
    id: 1,
    areaName: "Area A",
    rowName: "Row 1",
    image: "https://via.placeholder.com/150",
    fullName: "John Smith",
    name: "John",
    codeName: "JS123",
    yearOfBirth: "1920",
    dateOfEnlistment: "1941-01-01",
    dateOfDeath: "1944-05-05",
    rankPositionUnit: "Private",
    homeTown: "Town A",
    placeOfExhumation: "Place A",
    note: "Note 1",
    commune: "Commune A",
    district: "District A",
  },
  {
    id: 2,
    areaName: "Area B",
    rowName: "Row 2",
    image: "https://via.placeholder.com/150",
    fullName: "Alice Johnson",
    name: "Alice",
    codeName: "AJ456",
    yearOfBirth: "1922",
    dateOfEnlistment: "1942-02-02",
    dateOfDeath: "1945-06-06",
    rankPositionUnit: "Sergeant",
    homeTown: "Town B",
    placeOfExhumation: "Place B",
    note: "Note 2",
    commune: "Commune B",
    district: "District B",
  },
  {
    id: 3,
    areaName: "Area C",
    rowName: "Row 3",
    image: "https://via.placeholder.com/150",
    fullName: "Bob Williams",
    name: "Bob",
    codeName: "BW789",
    yearOfBirth: "1924",
    dateOfEnlistment: "1943-03-03",
    dateOfDeath: "1946-07-07",
    rankPositionUnit: "Lieutenant",
    homeTown: "Town C",
    placeOfExhumation: "Place C",
    note: "Note 3",
    commune: "Commune C",
    district: "District C",
  },
];
